// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.29.2
// source: cart-service/cart_item_service.proto

package cart

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CartItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Cart          string                 `protobuf:"bytes,2,opt,name=cart,proto3" json:"cart,omitempty"`
	Product       string                 `protobuf:"bytes,3,opt,name=product,proto3" json:"product,omitempty"`
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float32                `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	Currency      string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	SubTotal      float32                `protobuf:"fixed32,7,opt,name=sub_total,json=subTotal,proto3" json:"sub_total,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItemResponse) Reset() {
	*x = CartItemResponse{}
	mi := &file_cart_service_cart_item_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItemResponse) ProtoMessage() {}

func (x *CartItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_service_cart_item_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItemResponse.ProtoReflect.Descriptor instead.
func (*CartItemResponse) Descriptor() ([]byte, []int) {
	return file_cart_service_cart_item_service_proto_rawDescGZIP(), []int{0}
}

func (x *CartItemResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CartItemResponse) GetCart() string {
	if x != nil {
		return x.Cart
	}
	return ""
}

func (x *CartItemResponse) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *CartItemResponse) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CartItemResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CartItemResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CartItemResponse) GetSubTotal() float32 {
	if x != nil {
		return x.SubTotal
	}
	return 0
}

func (x *CartItemResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CartTxResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CartItem      *CartItemResponse      `protobuf:"bytes,1,opt,name=cart_item,json=cartItem,proto3" json:"cart_item,omitempty"`
	Cart          *Cart                  `protobuf:"bytes,2,opt,name=cart,proto3" json:"cart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartTxResult) Reset() {
	*x = CartTxResult{}
	mi := &file_cart_service_cart_item_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartTxResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartTxResult) ProtoMessage() {}

func (x *CartTxResult) ProtoReflect() protoreflect.Message {
	mi := &file_cart_service_cart_item_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartTxResult.ProtoReflect.Descriptor instead.
func (*CartTxResult) Descriptor() ([]byte, []int) {
	return file_cart_service_cart_item_service_proto_rawDescGZIP(), []int{1}
}

func (x *CartTxResult) GetCartItem() *CartItemResponse {
	if x != nil {
		return x.CartItem
	}
	return nil
}

func (x *CartTxResult) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

type RemoveCartTxResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cart          *Cart                  `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCartTxResult) Reset() {
	*x = RemoveCartTxResult{}
	mi := &file_cart_service_cart_item_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCartTxResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCartTxResult) ProtoMessage() {}

func (x *RemoveCartTxResult) ProtoReflect() protoreflect.Message {
	mi := &file_cart_service_cart_item_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCartTxResult.ProtoReflect.Descriptor instead.
func (*RemoveCartTxResult) Descriptor() ([]byte, []int) {
	return file_cart_service_cart_item_service_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveCartTxResult) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

type GetCartItemByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartItemByIDRequest) Reset() {
	*x = GetCartItemByIDRequest{}
	mi := &file_cart_service_cart_item_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartItemByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartItemByIDRequest) ProtoMessage() {}

func (x *GetCartItemByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_service_cart_item_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartItemByIDRequest.ProtoReflect.Descriptor instead.
func (*GetCartItemByIDRequest) Descriptor() ([]byte, []int) {
	return file_cart_service_cart_item_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetCartItemByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCartItemsByCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartItemsByCartRequest) Reset() {
	*x = GetCartItemsByCartRequest{}
	mi := &file_cart_service_cart_item_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartItemsByCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartItemsByCartRequest) ProtoMessage() {}

func (x *GetCartItemsByCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_service_cart_item_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartItemsByCartRequest.ProtoReflect.Descriptor instead.
func (*GetCartItemsByCartRequest) Descriptor() ([]byte, []int) {
	return file_cart_service_cart_item_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetCartItemsByCartRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCartItemsByCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CartItem      []*CartItemResponse    `protobuf:"bytes,1,rep,name=cart_item,json=cartItem,proto3" json:"cart_item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartItemsByCartResponse) Reset() {
	*x = GetCartItemsByCartResponse{}
	mi := &file_cart_service_cart_item_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartItemsByCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartItemsByCartResponse) ProtoMessage() {}

func (x *GetCartItemsByCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_service_cart_item_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartItemsByCartResponse.ProtoReflect.Descriptor instead.
func (*GetCartItemsByCartResponse) Descriptor() ([]byte, []int) {
	return file_cart_service_cart_item_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetCartItemsByCartResponse) GetCartItem() []*CartItemResponse {
	if x != nil {
		return x.CartItem
	}
	return nil
}

type GetCartItemByProductIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartItemByProductIDRequest) Reset() {
	*x = GetCartItemByProductIDRequest{}
	mi := &file_cart_service_cart_item_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartItemByProductIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartItemByProductIDRequest) ProtoMessage() {}

func (x *GetCartItemByProductIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_service_cart_item_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartItemByProductIDRequest.ProtoReflect.Descriptor instead.
func (*GetCartItemByProductIDRequest) Descriptor() ([]byte, []int) {
	return file_cart_service_cart_item_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetCartItemByProductIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AddtoCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddtoCartRequest) Reset() {
	*x = AddtoCartRequest{}
	mi := &file_cart_service_cart_item_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddtoCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddtoCartRequest) ProtoMessage() {}

func (x *AddtoCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_service_cart_item_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddtoCartRequest.ProtoReflect.Descriptor instead.
func (*AddtoCartRequest) Descriptor() ([]byte, []int) {
	return file_cart_service_cart_item_service_proto_rawDescGZIP(), []int{7}
}

func (x *AddtoCartRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *AddtoCartRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *AddtoCartRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateCartTxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCartTxRequest) Reset() {
	*x = UpdateCartTxRequest{}
	mi := &file_cart_service_cart_item_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCartTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCartTxRequest) ProtoMessage() {}

func (x *UpdateCartTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_service_cart_item_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCartTxRequest.ProtoReflect.Descriptor instead.
func (*UpdateCartTxRequest) Descriptor() ([]byte, []int) {
	return file_cart_service_cart_item_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateCartTxRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCartTxRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type RemoveCartTxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCartTxRequest) Reset() {
	*x = RemoveCartTxRequest{}
	mi := &file_cart_service_cart_item_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCartTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCartTxRequest) ProtoMessage() {}

func (x *RemoveCartTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_service_cart_item_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCartTxRequest.ProtoReflect.Descriptor instead.
func (*RemoveCartTxRequest) Descriptor() ([]byte, []int) {
	return file_cart_service_cart_item_service_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveCartTxRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_cart_service_cart_item_service_proto protoreflect.FileDescriptor

var file_cart_service_cart_item_service_proto_rawDesc = []byte{
	0x0a, 0x24, 0x63, 0x61, 0x72, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x63,
	0x61, 0x72, 0x74, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x61, 0x72, 0x74, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x63,
	0x61, 0x72, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x63, 0x61, 0x72, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf6, 0x01, 0x0a, 0x10, 0x43, 0x61, 0x72, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x61, 0x72, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x5f, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x73, 0x75, 0x62, 0x54,
	0x6f, 0x74, 0x61, 0x6c, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22,
	0x63, 0x0a, 0x0c, 0x43, 0x61, 0x72, 0x74, 0x54, 0x78, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x33, 0x0a, 0x09, 0x63, 0x61, 0x72, 0x74, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x43, 0x61, 0x72, 0x74, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x63, 0x61, 0x72, 0x74,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x1e, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x43, 0x61, 0x72, 0x74, 0x52, 0x04,
	0x63, 0x61, 0x72, 0x74, 0x22, 0x34, 0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x61,
	0x72, 0x74, 0x54, 0x78, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1e, 0x0a, 0x04, 0x63, 0x61,
	0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e,
	0x43, 0x61, 0x72, 0x74, 0x52, 0x04, 0x63, 0x61, 0x72, 0x74, 0x22, 0x28, 0x0a, 0x16, 0x47, 0x65,
	0x74, 0x43, 0x61, 0x72, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x2b, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x42, 0x79, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x51, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x74, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x42, 0x79, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x33, 0x0a, 0x09, 0x63, 0x61, 0x72, 0x74, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x43, 0x61, 0x72, 0x74, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x63, 0x61, 0x72, 0x74,
	0x49, 0x74, 0x65, 0x6d, 0x22, 0x2f, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x42, 0x79, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x66, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x74, 0x6f, 0x43, 0x61,
	0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x41, 0x0a,
	0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x74, 0x54, 0x78, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x22, 0x25, 0x0a, 0x13, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x61, 0x72, 0x74, 0x54, 0x78,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x32, 0xd1, 0x03, 0x0a, 0x0f, 0x43, 0x61, 0x72, 0x74,
	0x49, 0x74, 0x65, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x41,
	0x64, 0x64, 0x54, 0x6f, 0x43, 0x61, 0x72, 0x74, 0x54, 0x78, 0x12, 0x16, 0x2e, 0x63, 0x61, 0x72,
	0x74, 0x2e, 0x41, 0x64, 0x64, 0x74, 0x6f, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x12, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x43, 0x61, 0x72, 0x74, 0x54, 0x78,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x43, 0x61, 0x72, 0x74, 0x54, 0x78, 0x12, 0x19, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x74, 0x54, 0x78, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x43, 0x61, 0x72, 0x74, 0x54,
	0x78, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0c, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x43, 0x61, 0x72, 0x74, 0x54, 0x78, 0x12, 0x19, 0x2e, 0x63, 0x61, 0x72, 0x74,
	0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x61, 0x72, 0x74, 0x54, 0x78, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x43, 0x61, 0x72, 0x74, 0x54, 0x78, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00,
	0x12, 0x45, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12,
	0x1c, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x74, 0x49, 0x74,
	0x65, 0x6d, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x63, 0x61, 0x72, 0x74, 0x2e, 0x43, 0x61, 0x72, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43, 0x61,
	0x72, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x42, 0x79, 0x43, 0x61, 0x72, 0x74, 0x12, 0x1f, 0x2e,
	0x63, 0x61, 0x72, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x74, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x42, 0x79, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20,
	0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x42, 0x79, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x57, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x42, 0x79, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x12, 0x23, 0x2e, 0x63,
	0x61, 0x72, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x42,
	0x79, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x43, 0x61, 0x72, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x13, 0x5a, 0x11, 0x63,
	0x61, 0x72, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x63, 0x61, 0x72, 0x74,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cart_service_cart_item_service_proto_rawDescOnce sync.Once
	file_cart_service_cart_item_service_proto_rawDescData = file_cart_service_cart_item_service_proto_rawDesc
)

func file_cart_service_cart_item_service_proto_rawDescGZIP() []byte {
	file_cart_service_cart_item_service_proto_rawDescOnce.Do(func() {
		file_cart_service_cart_item_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_cart_service_cart_item_service_proto_rawDescData)
	})
	return file_cart_service_cart_item_service_proto_rawDescData
}

var file_cart_service_cart_item_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_cart_service_cart_item_service_proto_goTypes = []any{
	(*CartItemResponse)(nil),              // 0: cart.CartItemResponse
	(*CartTxResult)(nil),                  // 1: cart.CartTxResult
	(*RemoveCartTxResult)(nil),            // 2: cart.RemoveCartTxResult
	(*GetCartItemByIDRequest)(nil),        // 3: cart.GetCartItemByIDRequest
	(*GetCartItemsByCartRequest)(nil),     // 4: cart.GetCartItemsByCartRequest
	(*GetCartItemsByCartResponse)(nil),    // 5: cart.GetCartItemsByCartResponse
	(*GetCartItemByProductIDRequest)(nil), // 6: cart.GetCartItemByProductIDRequest
	(*AddtoCartRequest)(nil),              // 7: cart.AddtoCartRequest
	(*UpdateCartTxRequest)(nil),           // 8: cart.UpdateCartTxRequest
	(*RemoveCartTxRequest)(nil),           // 9: cart.RemoveCartTxRequest
	(*timestamppb.Timestamp)(nil),         // 10: google.protobuf.Timestamp
	(*Cart)(nil),                          // 11: cart.Cart
}
var file_cart_service_cart_item_service_proto_depIdxs = []int32{
	10, // 0: cart.CartItemResponse.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: cart.CartTxResult.cart_item:type_name -> cart.CartItemResponse
	11, // 2: cart.CartTxResult.cart:type_name -> cart.Cart
	11, // 3: cart.RemoveCartTxResult.cart:type_name -> cart.Cart
	0,  // 4: cart.GetCartItemsByCartResponse.cart_item:type_name -> cart.CartItemResponse
	7,  // 5: cart.CartItemService.AddToCartTx:input_type -> cart.AddtoCartRequest
	8,  // 6: cart.CartItemService.UpdateCartTx:input_type -> cart.UpdateCartTxRequest
	9,  // 7: cart.CartItemService.RemoveCartTx:input_type -> cart.RemoveCartTxRequest
	3,  // 8: cart.CartItemService.GetCartItem:input_type -> cart.GetCartItemByIDRequest
	4,  // 9: cart.CartItemService.GetCartItemsByCart:input_type -> cart.GetCartItemsByCartRequest
	6,  // 10: cart.CartItemService.GetCartItemByProductID:input_type -> cart.GetCartItemByProductIDRequest
	1,  // 11: cart.CartItemService.AddToCartTx:output_type -> cart.CartTxResult
	1,  // 12: cart.CartItemService.UpdateCartTx:output_type -> cart.CartTxResult
	2,  // 13: cart.CartItemService.RemoveCartTx:output_type -> cart.RemoveCartTxResult
	0,  // 14: cart.CartItemService.GetCartItem:output_type -> cart.CartItemResponse
	5,  // 15: cart.CartItemService.GetCartItemsByCart:output_type -> cart.GetCartItemsByCartResponse
	0,  // 16: cart.CartItemService.GetCartItemByProductID:output_type -> cart.CartItemResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_cart_service_cart_item_service_proto_init() }
func file_cart_service_cart_item_service_proto_init() {
	if File_cart_service_cart_item_service_proto != nil {
		return
	}
	file_cart_service_cart_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cart_service_cart_item_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cart_service_cart_item_service_proto_goTypes,
		DependencyIndexes: file_cart_service_cart_item_service_proto_depIdxs,
		MessageInfos:      file_cart_service_cart_item_service_proto_msgTypes,
	}.Build()
	File_cart_service_cart_item_service_proto = out.File
	file_cart_service_cart_item_service_proto_rawDesc = nil
	file_cart_service_cart_item_service_proto_goTypes = nil
	file_cart_service_cart_item_service_proto_depIdxs = nil
}
