// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Auction struct {
	ID            uuid.UUID `json:"id"`
	ProductID     string    `json:"product_id"`
	UserID        uuid.UUID `json:"user_id"`
	StartTime     time.Time `json:"start_time"`
	EndTime       time.Time `json:"end_time"`
	StartingPrice float64   `json:"starting_price"`
	CurrentPrice  float64   `json:"current_price"`
	// it can be active, suspended or ended
	Status    string    `json:"status"`
	WinnerID  uuid.UUID `json:"winner_id"`
	UpdatedAt time.Time `json:"updated_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Bid struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	AuctionID uuid.UUID `json:"auction_id"`
	Amount    float64   `json:"amount"`
	BidTime   time.Time `json:"bid_time"`
}
