// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAuction(ctx context.Context, arg CreateAuctionParams) (Auction, error)
	CreateBid(ctx context.Context, arg CreateBidParams) (Bid, error)
	GetAllAuctions(ctx context.Context) ([]Auction, error)
	GetAuction(ctx context.Context, id uuid.UUID) (Auction, error)
	GetAuctionForUpdate(ctx context.Context, id uuid.UUID) (Auction, error)
	GetBid(ctx context.Context, id uuid.UUID) (Bid, error)
	ListAuctions(ctx context.Context, arg ListAuctionsParams) ([]Auction, error)
	UpdateAuction(ctx context.Context, arg UpdateAuctionParams) (Auction, error)
}

var _ Querier = (*Queries)(nil)
