// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.0
//   protoc               v5.29.2
// source: user-service/rpc_login_user.proto

/* eslint-disable */
import { Timestamp } from "../google/protobuf/timestamp";
import { User } from "./user";

export const protobufPackage = "pb";

export interface LoginUserRequest {
  email: string;
  password: string;
}

export interface LoginUserResponse {
  user: User | undefined;
  sessionId: string;
  accessToken: string;
  refreshToken: string;
  accessTokenExpiresAt: Timestamp | undefined;
  refreshTokenExpiresAt: Timestamp | undefined;
}

export const PB_PACKAGE_NAME = "pb";
