// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.0
//   protoc               v5.29.2
// source: user-service/rpc_forgot_password.proto

/* eslint-disable */

export const protobufPackage = "pb";

export interface ForgotPasswordRequest {
  email: string;
}

export interface ForgotPasswordResponse {
  message: string;
}

export const PB_PACKAGE_NAME = "pb";
