version: "3.9"
services:
  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=mahanta
      - POSTGRES_DB=e_commerce_cart
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d e_commerce_cart"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7070:7070"
    environment:
      - DB_SOURCE=postgresql://root:mahanta@postgres:5432/e_commerce_cart?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy

    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
