// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.0
//   protoc               v5.29.2
// source: user.proto

/* eslint-disable */
import { Timestamp } from "./google/protobuf/timestamp";

export const protobufPackage = "pb";

export interface User {
  id: string;
  name: string;
  email: string;
  role: string;
  createdAt: Timestamp | undefined;
}

export const PB_PACKAGE_NAME = "pb";
