// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.0
//   protoc               v5.29.2
// source: cart-service/cart.proto

/* eslint-disable */

export const protobufPackage = "cart";

export interface Cart {
  id: string;
  userId: string;
  totalPrice: number;
}

export const CART_PACKAGE_NAME = "cart";
