// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: stripe_customer.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createStripeCustomer = `-- name: CreateStripeCustomer :one
INSERT INTO stripe_customers (
  id, 
  user_id
) VALUES (
  $1, $2
) RETURNING id, user_id, created_at
`

type CreateStripeCustomerParams struct {
	ID     string    `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateStripeCustomer(ctx context.Context, arg CreateStripeCustomerParams) (StripeCustomer, error) {
	row := q.db.QueryRowContext(ctx, createStripeCustomer, arg.ID, arg.UserID)
	var i StripeCustomer
	err := row.Scan(&i.ID, &i.UserID, &i.CreatedAt)
	return i, err
}

const getStripeCustomerById = `-- name: GetStripeCustomerById :one
SELECT id, user_id, created_at FROM stripe_customers 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetStripeCustomerById(ctx context.Context, id string) (StripeCustomer, error) {
	row := q.db.QueryRowContext(ctx, getStripeCustomerById, id)
	var i StripeCustomer
	err := row.Scan(&i.ID, &i.UserID, &i.CreatedAt)
	return i, err
}

const getStripeCustomerByUserId = `-- name: GetStripeCustomerByUserId :one
SELECT id, user_id, created_at FROM stripe_customers 
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetStripeCustomerByUserId(ctx context.Context, userID uuid.UUID) (StripeCustomer, error) {
	row := q.db.QueryRowContext(ctx, getStripeCustomerByUserId, userID)
	var i StripeCustomer
	err := row.Scan(&i.ID, &i.UserID, &i.CreatedAt)
	return i, err
}
