// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.0
//   protoc               v5.29.2
// source: product-service/file.proto

/* eslint-disable */

export const protobufPackage = "product";

export interface File {
  buffer: Uint8Array;
  originalname: string;
  fieldname: string;
  size: number;
  mimetype: string;
  encoding: string;
}

export const PRODUCT_PACKAGE_NAME = "product";
