// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.0
//   protoc               v3.12.4
// source: rpc_create_product.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { File } from "./file";
import { Any } from "./google/protobuf/any";
import { Product } from "./product";

export const protobufPackage = "pb";

export interface CreateProductRequest {
  category: string;
  productName: string;
  description: string;
  brand: string;
  image: File | undefined;
  countInStock: number;
  price: number;
  currency: string;
  shop: Any | undefined;
  rating: number;
  isFeatured: boolean;
}

export interface CreateProductResponse {
  message: string;
  product: Product | undefined;
}

function createBaseCreateProductRequest(): CreateProductRequest {
  return {
    category: "",
    productName: "",
    description: "",
    brand: "",
    image: undefined,
    countInStock: 0,
    price: 0,
    currency: "",
    shop: undefined,
    rating: 0,
    isFeatured: false,
  };
}

export const CreateProductRequest: MessageFns<CreateProductRequest> = {
  encode(message: CreateProductRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.category !== "") {
      writer.uint32(10).string(message.category);
    }
    if (message.productName !== "") {
      writer.uint32(18).string(message.productName);
    }
    if (message.description !== "") {
      writer.uint32(26).string(message.description);
    }
    if (message.brand !== "") {
      writer.uint32(34).string(message.brand);
    }
    if (message.image !== undefined) {
      File.encode(message.image, writer.uint32(42).fork()).join();
    }
    if (message.countInStock !== 0) {
      writer.uint32(48).int64(message.countInStock);
    }
    if (message.price !== 0) {
      writer.uint32(61).float(message.price);
    }
    if (message.currency !== "") {
      writer.uint32(66).string(message.currency);
    }
    if (message.shop !== undefined) {
      Any.encode(message.shop, writer.uint32(74).fork()).join();
    }
    if (message.rating !== 0) {
      writer.uint32(80).int64(message.rating);
    }
    if (message.isFeatured !== false) {
      writer.uint32(88).bool(message.isFeatured);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateProductRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateProductRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.category = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.productName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.brand = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.image = File.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.countInStock = longToNumber(reader.int64());
          continue;
        }
        case 7: {
          if (tag !== 61) {
            break;
          }

          message.price = reader.float();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.currency = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.shop = Any.decode(reader, reader.uint32());
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.rating = longToNumber(reader.int64());
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.isFeatured = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateProductRequest {
    return {
      category: isSet(object.category) ? globalThis.String(object.category) : "",
      productName: isSet(object.productName) ? globalThis.String(object.productName) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      brand: isSet(object.brand) ? globalThis.String(object.brand) : "",
      image: isSet(object.image) ? File.fromJSON(object.image) : undefined,
      countInStock: isSet(object.countInStock) ? globalThis.Number(object.countInStock) : 0,
      price: isSet(object.price) ? globalThis.Number(object.price) : 0,
      currency: isSet(object.currency) ? globalThis.String(object.currency) : "",
      shop: isSet(object.shop) ? Any.fromJSON(object.shop) : undefined,
      rating: isSet(object.rating) ? globalThis.Number(object.rating) : 0,
      isFeatured: isSet(object.isFeatured) ? globalThis.Boolean(object.isFeatured) : false,
    };
  },

  toJSON(message: CreateProductRequest): unknown {
    const obj: any = {};
    if (message.category !== "") {
      obj.category = message.category;
    }
    if (message.productName !== "") {
      obj.productName = message.productName;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.brand !== "") {
      obj.brand = message.brand;
    }
    if (message.image !== undefined) {
      obj.image = File.toJSON(message.image);
    }
    if (message.countInStock !== 0) {
      obj.countInStock = Math.round(message.countInStock);
    }
    if (message.price !== 0) {
      obj.price = message.price;
    }
    if (message.currency !== "") {
      obj.currency = message.currency;
    }
    if (message.shop !== undefined) {
      obj.shop = Any.toJSON(message.shop);
    }
    if (message.rating !== 0) {
      obj.rating = Math.round(message.rating);
    }
    if (message.isFeatured !== false) {
      obj.isFeatured = message.isFeatured;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateProductRequest>, I>>(base?: I): CreateProductRequest {
    return CreateProductRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateProductRequest>, I>>(object: I): CreateProductRequest {
    const message = createBaseCreateProductRequest();
    message.category = object.category ?? "";
    message.productName = object.productName ?? "";
    message.description = object.description ?? "";
    message.brand = object.brand ?? "";
    message.image = (object.image !== undefined && object.image !== null) ? File.fromPartial(object.image) : undefined;
    message.countInStock = object.countInStock ?? 0;
    message.price = object.price ?? 0;
    message.currency = object.currency ?? "";
    message.shop = (object.shop !== undefined && object.shop !== null) ? Any.fromPartial(object.shop) : undefined;
    message.rating = object.rating ?? 0;
    message.isFeatured = object.isFeatured ?? false;
    return message;
  },
};

function createBaseCreateProductResponse(): CreateProductResponse {
  return { message: "", product: undefined };
}

export const CreateProductResponse: MessageFns<CreateProductResponse> = {
  encode(message: CreateProductResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    if (message.product !== undefined) {
      Product.encode(message.product, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateProductResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateProductResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.product = Product.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateProductResponse {
    return {
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      product: isSet(object.product) ? Product.fromJSON(object.product) : undefined,
    };
  },

  toJSON(message: CreateProductResponse): unknown {
    const obj: any = {};
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.product !== undefined) {
      obj.product = Product.toJSON(message.product);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateProductResponse>, I>>(base?: I): CreateProductResponse {
    return CreateProductResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateProductResponse>, I>>(object: I): CreateProductResponse {
    const message = createBaseCreateProductResponse();
    message.message = object.message ?? "";
    message.product = (object.product !== undefined && object.product !== null)
      ? Product.fromPartial(object.product)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
