// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.0
//   protoc               v3.12.4
// source: shop_service.proto

/* eslint-disable */
import { BinaryReader } from "@bufbuild/protobuf/wire";
import { CreateShopRequest, CreateShopResponse } from "./rpc_create_shop";

export const protobufPackage = "pb";

export interface ShopService {
  CreateShop(request: CreateShopRequest): Promise<CreateShopResponse>;
}

export const ShopServiceServiceName = "pb.ShopService";
export class ShopServiceClientImpl implements ShopService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || ShopServiceServiceName;
    this.rpc = rpc;
    this.CreateShop = this.CreateShop.bind(this);
  }
  CreateShop(request: CreateShopRequest): Promise<CreateShopResponse> {
    const data = CreateShopRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "CreateShop", data);
    return promise.then((data) => CreateShopResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}
