// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddSubtotalPrice(ctx context.Context, cart uuid.UUID) (float64, error)
	CreateCart(ctx context.Context, arg CreateCartParams) (Cart, error)
	CreateCartitem(ctx context.Context, arg CreateCartitemParams) (Cartitem, error)
	DeleteCartitem(ctx context.Context, id uuid.UUID) error
	GetALLCartitemsForUpdate(ctx context.Context) ([]Cartitem, error)
	GetAllCartitems(ctx context.Context) ([]Cartitem, error)
	GetCart(ctx context.Context, id uuid.UUID) (Cart, error)
	GetCartByUserID(ctx context.Context, userID uuid.UUID) (Cart, error)
	GetCartForUpdate(ctx context.Context, id uuid.UUID) (Cart, error)
	GetCartitem(ctx context.Context, id uuid.UUID) (Cartitem, error)
	GetCartitemByProductID(ctx context.Context, product string) (Cartitem, error)
	GetCartitemForUpdate(ctx context.Context, id uuid.UUID) (Cartitem, error)
	GetCartitemsByCartID(ctx context.Context, cart uuid.UUID) ([]Cartitem, error)
	ListCartitems(ctx context.Context, arg ListCartitemsParams) ([]Cartitem, error)
	UpdateCart(ctx context.Context, arg UpdateCartParams) (Cart, error)
	UpdateCartitem(ctx context.Context, arg UpdateCartitemParams) (Cartitem, error)
}

var _ Querier = (*Queries)(nil)
