// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: cart_item_service.proto

package cart

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CartItemService_AddToCart_FullMethodName              = "/cart.CartItemService/AddToCart"
	CartItemService_CreateCartItem_FullMethodName         = "/cart.CartItemService/CreateCartItem"
	CartItemService_GetCartItem_FullMethodName            = "/cart.CartItemService/GetCartItem"
	CartItemService_GetCartItemsByCart_FullMethodName     = "/cart.CartItemService/GetCartItemsByCart"
	CartItemService_GetCartItemByProductID_FullMethodName = "/cart.CartItemService/GetCartItemByProductID"
)

// CartItemServiceClient is the client API for CartItemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CartItemServiceClient interface {
	AddToCart(ctx context.Context, in *AddtoCartRequest, opts ...grpc.CallOption) (*CartTxResult, error)
	CreateCartItem(ctx context.Context, in *CreateCartItemRequest, opts ...grpc.CallOption) (*CartItemResponse, error)
	GetCartItem(ctx context.Context, in *GetCartItemByIDRequest, opts ...grpc.CallOption) (*CartItemResponse, error)
	GetCartItemsByCart(ctx context.Context, in *GetCartItemsByCartRequest, opts ...grpc.CallOption) (*GetCartItemsByCartResponse, error)
	GetCartItemByProductID(ctx context.Context, in *GetCartItemByProductIDRequest, opts ...grpc.CallOption) (*CartItemResponse, error)
}

type cartItemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCartItemServiceClient(cc grpc.ClientConnInterface) CartItemServiceClient {
	return &cartItemServiceClient{cc}
}

func (c *cartItemServiceClient) AddToCart(ctx context.Context, in *AddtoCartRequest, opts ...grpc.CallOption) (*CartTxResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CartTxResult)
	err := c.cc.Invoke(ctx, CartItemService_AddToCart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartItemServiceClient) CreateCartItem(ctx context.Context, in *CreateCartItemRequest, opts ...grpc.CallOption) (*CartItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CartItemResponse)
	err := c.cc.Invoke(ctx, CartItemService_CreateCartItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartItemServiceClient) GetCartItem(ctx context.Context, in *GetCartItemByIDRequest, opts ...grpc.CallOption) (*CartItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CartItemResponse)
	err := c.cc.Invoke(ctx, CartItemService_GetCartItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartItemServiceClient) GetCartItemsByCart(ctx context.Context, in *GetCartItemsByCartRequest, opts ...grpc.CallOption) (*GetCartItemsByCartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCartItemsByCartResponse)
	err := c.cc.Invoke(ctx, CartItemService_GetCartItemsByCart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartItemServiceClient) GetCartItemByProductID(ctx context.Context, in *GetCartItemByProductIDRequest, opts ...grpc.CallOption) (*CartItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CartItemResponse)
	err := c.cc.Invoke(ctx, CartItemService_GetCartItemByProductID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CartItemServiceServer is the server API for CartItemService service.
// All implementations must embed UnimplementedCartItemServiceServer
// for forward compatibility.
type CartItemServiceServer interface {
	AddToCart(context.Context, *AddtoCartRequest) (*CartTxResult, error)
	CreateCartItem(context.Context, *CreateCartItemRequest) (*CartItemResponse, error)
	GetCartItem(context.Context, *GetCartItemByIDRequest) (*CartItemResponse, error)
	GetCartItemsByCart(context.Context, *GetCartItemsByCartRequest) (*GetCartItemsByCartResponse, error)
	GetCartItemByProductID(context.Context, *GetCartItemByProductIDRequest) (*CartItemResponse, error)
	mustEmbedUnimplementedCartItemServiceServer()
}

// UnimplementedCartItemServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCartItemServiceServer struct{}

func (UnimplementedCartItemServiceServer) AddToCart(context.Context, *AddtoCartRequest) (*CartTxResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToCart not implemented")
}
func (UnimplementedCartItemServiceServer) CreateCartItem(context.Context, *CreateCartItemRequest) (*CartItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCartItem not implemented")
}
func (UnimplementedCartItemServiceServer) GetCartItem(context.Context, *GetCartItemByIDRequest) (*CartItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCartItem not implemented")
}
func (UnimplementedCartItemServiceServer) GetCartItemsByCart(context.Context, *GetCartItemsByCartRequest) (*GetCartItemsByCartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCartItemsByCart not implemented")
}
func (UnimplementedCartItemServiceServer) GetCartItemByProductID(context.Context, *GetCartItemByProductIDRequest) (*CartItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCartItemByProductID not implemented")
}
func (UnimplementedCartItemServiceServer) mustEmbedUnimplementedCartItemServiceServer() {}
func (UnimplementedCartItemServiceServer) testEmbeddedByValue()                         {}

// UnsafeCartItemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CartItemServiceServer will
// result in compilation errors.
type UnsafeCartItemServiceServer interface {
	mustEmbedUnimplementedCartItemServiceServer()
}

func RegisterCartItemServiceServer(s grpc.ServiceRegistrar, srv CartItemServiceServer) {
	// If the following call pancis, it indicates UnimplementedCartItemServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CartItemService_ServiceDesc, srv)
}

func _CartItemService_AddToCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddtoCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartItemServiceServer).AddToCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CartItemService_AddToCart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartItemServiceServer).AddToCart(ctx, req.(*AddtoCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartItemService_CreateCartItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCartItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartItemServiceServer).CreateCartItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CartItemService_CreateCartItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartItemServiceServer).CreateCartItem(ctx, req.(*CreateCartItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartItemService_GetCartItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCartItemByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartItemServiceServer).GetCartItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CartItemService_GetCartItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartItemServiceServer).GetCartItem(ctx, req.(*GetCartItemByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartItemService_GetCartItemsByCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCartItemsByCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartItemServiceServer).GetCartItemsByCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CartItemService_GetCartItemsByCart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartItemServiceServer).GetCartItemsByCart(ctx, req.(*GetCartItemsByCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartItemService_GetCartItemByProductID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCartItemByProductIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartItemServiceServer).GetCartItemByProductID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CartItemService_GetCartItemByProductID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartItemServiceServer).GetCartItemByProductID(ctx, req.(*GetCartItemByProductIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CartItemService_ServiceDesc is the grpc.ServiceDesc for CartItemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CartItemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cart.CartItemService",
	HandlerType: (*CartItemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddToCart",
			Handler:    _CartItemService_AddToCart_Handler,
		},
		{
			MethodName: "CreateCartItem",
			Handler:    _CartItemService_CreateCartItem_Handler,
		},
		{
			MethodName: "GetCartItem",
			Handler:    _CartItemService_GetCartItem_Handler,
		},
		{
			MethodName: "GetCartItemsByCart",
			Handler:    _CartItemService_GetCartItemsByCart_Handler,
		},
		{
			MethodName: "GetCartItemByProductID",
			Handler:    _CartItemService_GetCartItemByProductID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cart_item_service.proto",
}
